import { ThemeConfig, ThemePreset, Profile, LinkItem, SocialIconItem } from '../types';

export const FONT_OPTIONS = [
  { id: 'Plus Jakarta Sans', label: 'Plus Jakarta Sans', fontClass: 'font-["Plus_Jakarta_Sans",sans-serif]' },
  { id: 'Inter', label: 'Inter', fontClass: 'font-["Inter",sans-serif]' },
  { id: 'Outfit', label: 'Outfit', fontClass: 'font-["Outfit",sans-serif]' },
  { id: 'Playfair Display', label: 'Playfair Display (Serif)', fontClass: 'font-["Playfair_Display",serif]' },
  { id: 'Space Grotesk', label: 'Space Grotesk (Tech)', fontClass: 'font-["Space_Grotesk",sans-serif]' },
  { id: 'JetBrains Mono', label: 'JetBrains Mono (Code)', fontClass: 'font-["JetBrains_Mono",monospace]' },
];

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'gradient-midnight',
    name: 'Midnight Obsidian',
    category: 'dark',
    previewBg: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #000000 100%)',
    theme: {
      bg_type: 'preset',
      bg_value: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #000000 100%)',
      button_style: 'rounded',
      button_bg: 'rgba(30, 41, 59, 0.85)',
      button_text: '#ffffff',
      accent_color: '#818cf8',
      font_family: 'Plus Jakarta Sans',
      show_view_count: false,
    },
  },
  {
    id: 'gradient-sunset',
    name: 'Sunset Ember',
    category: 'vibrant',
    previewBg: 'linear-gradient(135deg, #4c0519 0%, #831843 40%, #18181b 100%)',
    theme: {
      bg_type: 'preset',
      bg_value: 'linear-gradient(135deg, #4c0519 0%, #831843 40%, #18181b 100%)',
      button_style: 'pill',
      button_bg: 'rgba(244, 63, 94, 0.2)',
      button_text: '#ffffff',
      accent_color: '#fb7185',
      font_family: 'Outfit',
      show_view_count: false,
    },
  },
  {
    id: 'clean-slate',
    name: 'Clean Studio',
    category: 'light',
    previewBg: 'linear-gradient(180deg, #f8fafc 0%, #f1f5f9 100%)',
    theme: {
      bg_type: 'preset',
      bg_value: 'linear-gradient(180deg, #f8fafc 0%, #f1f5f9 100%)',
      button_style: 'shadow',
      button_bg: '#ffffff',
      button_text: '#0f172a',
      accent_color: '#2563eb',
      font_family: 'Inter',
      show_view_count: false,
    },
  },
  {
    id: 'emerald-luxury',
    name: 'Deep Emerald',
    category: 'dark',
    previewBg: 'linear-gradient(135deg, #064e3b 0%, #022c22 60%, #000000 100%)',
    theme: {
      bg_type: 'preset',
      bg_value: 'linear-gradient(135deg, #064e3b 0%, #022c22 60%, #000000 100%)',
      button_style: 'glass',
      button_bg: 'rgba(6, 78, 59, 0.4)',
      button_text: '#ecfdf5',
      accent_color: '#34d399',
      font_family: 'Playfair Display',
      show_view_count: false,
    },
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    category: 'vibrant',
    previewBg: 'linear-gradient(135deg, #0a0a0f 0%, #1e0533 60%, #000000 100%)',
    theme: {
      bg_type: 'preset',
      bg_value: 'linear-gradient(135deg, #0a0a0f 0%, #1e0533 60%, #000000 100%)',
      button_style: 'outline',
      button_bg: 'rgba(15, 10, 25, 0.7)',
      button_text: '#22d3ee',
      accent_color: '#f43f5e',
      font_family: 'Space Grotesk',
      show_view_count: false,
    },
  },
  {
    id: 'warm-sand',
    name: 'Warm Paper',
    category: 'light',
    previewBg: 'linear-gradient(180deg, #fdfbf7 0%, #f5eedc 100%)',
    theme: {
      bg_type: 'preset',
      bg_value: 'linear-gradient(180deg, #fdfbf7 0%, #f5eedc 100%)',
      button_style: 'rounded',
      button_bg: '#ffffff',
      button_text: '#451a03',
      accent_color: '#d97706',
      font_family: 'Playfair Display',
      show_view_count: false,
    },
  },
];

export const SOCIAL_PLATFORMS = [
  { id: 'github', label: 'GitHub', placeholder: 'https://github.com/username' },
  { id: 'x', label: 'X (Twitter)', placeholder: 'https://x.com/username' },
  { id: 'linkedin', label: 'LinkedIn', placeholder: 'https://linkedin.com/in/username' },
  { id: 'instagram', label: 'Instagram', placeholder: 'https://instagram.com/username' },
  { id: 'youtube', label: 'YouTube', placeholder: 'https://youtube.com/@channel' },
  { id: 'medium', label: 'Medium', placeholder: 'https://medium.com/@username' },
  { id: 'kaggle', label: 'Kaggle', placeholder: 'https://kaggle.com/username' },
  { id: 'tiktok', label: 'TikTok', placeholder: 'https://tiktok.com/@username' },
  { id: 'twitch', label: 'Twitch', placeholder: 'https://twitch.tv/username' },
  { id: 'discord', label: 'Discord', placeholder: 'https://discord.gg/invite' },
  { id: 'spotify', label: 'Spotify', placeholder: 'https://open.spotify.com/artist/...' },
  { id: 'email', label: 'Email', placeholder: 'mailto:name@example.com' },
  { id: 'website', label: 'Portfolio / Website', placeholder: 'https://yourwebsite.com' },
];

export const LINK_ICONS = [
  'globe', 'github', 'twitter', 'instagram', 'youtube', 'linkedin', 'tiktok', 'spotify', 'discord', 'twitch',
  'facebook', 'threads', 'telegram', 'whatsapp', 'reddit', 'dribbble', 'behance', 'figma', 'pinterest',
  'medium', 'substack', 'kaggle', 'patreon', 'notion', 'steam', 'soundcloud', 'gitlab', 'slack',
  'briefcase', 'code', 'book-open', 'sparkles', 'star', 'music', 'video', 'shopping-bag', 'coffee',
  'camera', 'heart', 'podcast', 'file-text', 'zap', 'send', 'terminal', 'rocket', 'calendar', 'mail'
];

export const DEFAULT_AVATARS = [
  '/avatar-silvio.png',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
  'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
];

export const DEFAULT_LINK_CATEGORIES = ['Social', 'Work', 'Projects', 'Personal', 'Resources', 'Other'] as const;

// Initial seed data for "silvio" as requested by user
export const SEED_PROFILE_SILVIO: Profile = {
  id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
  user_id: 'user-silvio-001',
  username: 'silvio',
  display_name: 'Silvio Christian Joe',
  bio: 'AI Engineer & Full-Stack Developer 🚀\nCheck out my portfolio, Kaggle models, and open-source projects below.',
  avatar_url: '/avatar-silvio.png',
  meta_title: 'Silvio Christian Joe – AI Engineer & Full-Stack Developer',
  meta_description: 'Official portfolio and links of Silvio Christian Joe. Explore AI applications, Kaggle models, GitHub projects, and engineering updates.',
  theme: {
    bg_type: 'preset',
    bg_value: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #000000 100%)',
    button_style: 'rounded',
    button_bg: 'rgba(30, 41, 59, 0.85)',
    button_text: '#ffffff',
    accent_color: '#818cf8',
    font_family: 'Plus Jakarta Sans',
    show_view_count: false,
    show_discover_tab: true,
  },
  view_count: 0,
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
};

export const SEED_LINKS_SILVIO: LinkItem[] = [
  {
    id: 'link-01',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    title: 'AI & Full-Stack Engineering Portfolio',
    url: 'https://silvio-ai-portfolio.vercel.app/',
    icon: 'briefcase',
    description: 'Production AI systems, intelligent web applications, and technical project showcases.',
    category: 'Work',
    position: 0,
    is_active: true,
    is_featured: true,
    start_date: null,
    end_date: null,
    click_count: 52,
    last_clicked_at: new Date(Date.now() - 15 * 60000).toISOString(),
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'link-04',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    title: 'LinkedIn Professional Profile',
    url: 'https://www.linkedin.com/in/silvio-christian-joe',
    icon: 'linkedin',
    description: 'Connect for technical collaborations, career milestones, and engineering network.',
    category: 'Connect',
    position: 1,
    is_active: true,
    is_featured: true,
    start_date: null,
    end_date: null,
    click_count: 38,
    last_clicked_at: new Date(Date.now() - 45 * 60000).toISOString(),
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'link-03',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    title: 'GitHub Open Source Repositories',
    url: 'https://github.com/viochris',
    icon: 'github',
    description: 'Open-source machine learning codebases, full-stack templates, and developer tooling.',
    category: 'Projects',
    position: 2,
    is_active: true,
    is_featured: true,
    start_date: null,
    end_date: null,
    click_count: 46,
    last_clicked_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'link-02',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    title: 'Kaggle Data Science & ML Benchmarks',
    url: 'https://www.kaggle.com/viochristian',
    icon: 'kaggle',
    description: 'Competitive machine learning models, notebooks, and tabular benchmarks.',
    category: 'Projects',
    position: 3,
    is_active: true,
    is_featured: false,
    start_date: null,
    end_date: null,
    click_count: 29,
    last_clicked_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 24 * 86400000).toISOString(),
  },
  {
    id: 'link-05',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    title: 'Tech Insights & Build Logs on X',
    url: 'https://x.com/SilvioCodes',
    icon: 'x',
    description: 'Real-time engineering thoughts, AI agent architectures, and shipping updates.',
    category: 'Social',
    position: 4,
    is_active: true,
    is_featured: false,
    start_date: null,
    end_date: null,
    click_count: 27,
    last_clicked_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'link-06',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    title: 'Coding Lifestyle & Setups on Instagram',
    url: 'https://www.instagram.com/silvio.codes',
    icon: 'instagram',
    description: 'Behind-the-screens engineering, workspace setups, and dev journeys.',
    category: 'Social',
    position: 5,
    is_active: true,
    is_featured: false,
    start_date: null,
    end_date: null,
    click_count: 21,
    last_clicked_at: new Date(Date.now() - 18 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'link-08',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    title: 'Technical Deep-Dives on Medium',
    url: 'https://medium.com/@silviochristian',
    icon: 'medium',
    description: 'System design articles, AI tutorials, and full-stack software architecture.',
    category: 'Writing',
    position: 6,
    is_active: true,
    is_featured: false,
    start_date: null,
    end_date: null,
    click_count: 18,
    last_clicked_at: new Date(Date.now() - 24 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'link-09',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    title: 'YouTube Tech & Code Walkthroughs',
    url: 'https://youtube.com/@silviocodes',
    icon: 'youtube',
    description: 'Video tutorials, codebase walkthroughs, and live coding demos.',
    category: 'Video',
    position: 7,
    is_active: true,
    is_featured: false,
    start_date: null,
    end_date: null,
    click_count: 31,
    last_clicked_at: new Date(Date.now() - 30 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'link-07',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    title: 'Direct Inquiries & Collaboration',
    url: 'mailto:viochristian860@gmail.com',
    icon: 'mail',
    description: 'Reach out directly for freelance projects, AI consulting, or speaking engagements.',
    category: 'Contact',
    position: 8,
    is_active: true,
    is_featured: false,
    start_date: null,
    end_date: null,
    click_count: 12,
    last_clicked_at: new Date(Date.now() - 48 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const SEED_SOCIAL_SILVIO: SocialIconItem[] = [
  {
    id: 'social-01',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    platform: 'github',
    url: 'https://github.com/viochris',
    position: 0,
  },
  {
    id: 'social-02',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    platform: 'linkedin',
    url: 'https://www.linkedin.com/in/silvio-christian-joe',
    position: 1,
  },
  {
    id: 'social-03',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    platform: 'x',
    url: 'https://x.com/SilvioCodes',
    position: 2,
  },
  {
    id: 'social-04',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    platform: 'instagram',
    url: 'https://www.instagram.com/silvio.codes',
    position: 3,
  },
  {
    id: 'social-05',
    profile_id: 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d',
    platform: 'email',
    url: 'mailto:viochristian860@gmail.com',
    position: 4,
  },
];

// Seed profile for public "Try Demo" mode - separated from Silvio's authentic account
export const SEED_PROFILE_DEMO: Profile = {
  id: 'd1e00000-0000-4000-8000-000000000001',
  user_id: 'user-demo-001',
  username: 'demo',
  display_name: 'Alex Rivera',
  bio: 'Creative Technologist & UI Engineer ✨\nExploring AI-powered design systems, WebGL interactions, and modern web products.',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  meta_title: 'Alex Rivera – Creative Technologist & UI Engineer',
  meta_description: 'Explore Alex Rivera\'s portfolio, open-source design systems, UI components, and curated creative tech resources.',
  theme: {
    bg_type: 'preset',
    bg_value: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #000000 100%)',
    button_style: 'rounded',
    button_bg: 'rgba(30, 41, 59, 0.85)',
    button_text: '#ffffff',
    accent_color: '#818cf8',
    font_family: 'Plus Jakarta Sans',
    show_view_count: false,
    show_discover_tab: true,
  },
  view_count: 142,
  created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
};

// Seed links for the "Try Demo" profile:
// Polished, realistic, and pristine links
export const SEED_LINKS_DEMO: LinkItem[] = [
  {
    id: 'demo-link-01',
    profile_id: 'd1e00000-0000-4000-8000-000000000001',
    title: '🌐 Interactive Design & Systems Portfolio',
    url: 'https://silvio-ai-portfolio.vercel.app/',
    icon: 'briefcase',
    description: 'Showcase of production web apps, generative UI, and interactive prototypes.',
    category: 'Work',
    position: 0,
    is_active: true,
    is_featured: true,
    start_date: null,
    end_date: null,
    click_count: 54,
    last_clicked_at: new Date(Date.now() - 25 * 60000).toISOString(),
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'demo-link-02',
    profile_id: 'd1e00000-0000-4000-8000-000000000001',
    title: '💻 GitHub & Open Source Codebases',
    url: 'https://github.com/viochris',
    icon: 'code',
    description: 'Explore full-stack repositories, developer tooling, and modern web templates.',
    category: 'Projects',
    position: 1,
    is_active: true,
    is_featured: true,
    start_date: null,
    end_date: null,
    click_count: 42,
    last_clicked_at: new Date(Date.now() - 90 * 60000).toISOString(),
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'demo-link-03',
    profile_id: 'd1e00000-0000-4000-8000-000000000001',
    title: '💼 Connect on LinkedIn',
    url: 'https://www.linkedin.com/in/silvio-christian-joe',
    icon: 'linkedin',
    description: 'Product leadership, engineering discussions, and professional network.',
    category: 'Social',
    position: 2,
    is_active: true,
    is_featured: false,
    start_date: null,
    end_date: null,
    click_count: 36,
    last_clicked_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'demo-link-04',
    profile_id: 'd1e00000-0000-4000-8000-000000000001',
    title: '✨ Curated Design Tokens & Figma Kits',
    url: 'https://figma.com',
    icon: 'sparkles',
    description: 'Free community design assets, icon packs, and layout grids.',
    category: 'Resources',
    position: 3,
    is_active: true,
    is_featured: false,
    start_date: null,
    end_date: null,
    click_count: 28,
    last_clicked_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'demo-link-05',
    profile_id: 'd1e00000-0000-4000-8000-000000000001',
    title: '✉️ Weekly Creative Tech Newsletter',
    url: 'https://substack.com',
    icon: 'mail',
    description: 'Deep dives on frontend architectures, AI toolchains, and typography.',
    category: 'Personal',
    position: 4,
    is_active: true,
    is_featured: false,
    start_date: null,
    end_date: null,
    click_count: 21,
    last_clicked_at: new Date(Date.now() - 16 * 3600000).toISOString(),
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
];

// Seed social icons for "Try Demo" (without Medium, Kaggle, or private email)
export const SEED_SOCIAL_DEMO: SocialIconItem[] = [
  {
    id: 'demo-soc-01',
    profile_id: 'd1e00000-0000-4000-8000-000000000001',
    platform: 'github',
    url: 'https://github.com/viochris',
    position: 0,
  },
  {
    id: 'demo-soc-02',
    profile_id: 'd1e00000-0000-4000-8000-000000000001',
    platform: 'x',
    url: 'https://x.com/SilvioCodes',
    position: 1,
  },
  {
    id: 'demo-soc-03',
    profile_id: 'd1e00000-0000-4000-8000-000000000001',
    platform: 'linkedin',
    url: 'https://www.linkedin.com/in/silvio-christian-joe',
    position: 2,
  },
  {
    id: 'demo-soc-04',
    profile_id: 'd1e00000-0000-4000-8000-000000000001',
    platform: 'instagram',
    url: 'https://www.instagram.com/silvio.codes',
    position: 3,
  },
  {
    id: 'demo-soc-05',
    profile_id: 'd1e00000-0000-4000-8000-000000000001',
    platform: 'youtube',
    url: 'https://youtube.com/@silviocodes',
    position: 4,
  },
];
